---
  - name: Check if Workspace already exists
    win_stat:
      path: '{{ ansible_env.USERPROFILE }}\workspace'
    register: WorkspaceAlreadyExists
    
  - name: Download Eclipse workspace Project settings
    win_get_url:
      url: '{{ DOWNLOAD_URL }}/{{ WORKSPACE_FILE }}'
      dest: '{{ DOWNLOAD_DIR }}\eclipse\{{ WORKSPACE_FILE }}'
      force: no
    register: UnzipWorkspace
    when: WorkspaceAlreadyExists.stat.exists != True

  - name: Unzip Eclipse workspace setttings to USER workspace
    win_unzip:
      src: '{{ DOWNLOAD_DIR }}\eclipse\{{ WORKSPACE_FILE }}'
      dest: '{{ ansible_env.USERPROFILE }}'
      creates: '{{ ansible_env.USERPROFILE }}\workspace'
    when: not UnzipWorkspace.skipped