---
  - name: Download Eclipse workspace Project settings
    win_get_url:
      url: "{{ DOWNLOAD_URL }}/{{ WORKSPACE_FILE }}"
      dest: "{{ DOWNLOAD_DIR }}\\eclipse\\{{ WORKSPACE_FILE }}"
      force: no

  - name: Unzip Eclipse workspace setttings to USER workspace
    win_unzip:
      src: "{{ DOWNLOAD_DIR }}\\eclipse\\{{ WORKSPACE_FILE }}"
      dest: "{{ ansible_env.USERPROFILE }}"
      creates: "{{ ansible_env.USERPROFILE }}\\workspace"