---
- hosts: all
  gather_facts: false
  tasks:
    - name: Check for single host
      fail: msg="Single host check failed."
      when: "{{ play_hosts|length }} != 1"
    - debug: msg='I got executed!'
    
    - name: Enable Gather Facts
      setup:
  #roles:
  #  - common
  #  - git
  #  - java
  #  - tomcat
  #  - mysql
  #  - eclipse
