---
  - name: Download MySQL
    win_get_url:
      url: '{{ DOWNLOAD_URL }}/{{ MYSQL_VERSION }}'
      dest: '{{ DOWNLOAD_DIR }}\mysql\{{ MYSQL_VERSION}}'

  - name: Install MySQL 5
    script: scripts/MySQL_Install.ps1 '{{ DOWNLOAD_DIR }}\mysql\{{ MYSQL_VERSION}}' '{{ DOWNLOAD_DIR }}\mysql\MySQL_Install.log'
    register: available

  - name: Configure MySQL Instance
    script: 'Start-Process -verb RunAs -FilePath \"$env:ProgramFiles\MySQL\MySQL Server 5.5\bin\mysqlinstanceconfig.exe" -ArgumentList "-i -q ServiceName=MySQL RootPassword=mysql Port=3306 Charset=utf8\" -PassThru -Wait'
    
  - name: Add MySQL to System PATH
    script: scripts/AddPath.ps1 "%ProgramFiles%\MySQL\MySQL Server 5.5\bin" User
    
  - name: Create Sample PETCLINIC DB
    script: cmd.exe /c mysql --user=root --password=mysql -e "CREATE DATABASE PETCLINIC;"
    register: dbout
