---
  - name: Check if JDK 1.7 already present
    win_stat:
      path: '{{ ansible_env.ProgramFiles }}\jdk{{ JAVA_VERSION }}\bin\javac.exe'
    register: JDKInstallStatus
    
  - name: Download JDK 7
    win_get_url:
      url: '{{ DOWNLOAD_URL }}/{{ JAVA_EXE_FILE }}'
      dest: '{{ DOWNLOAD_DIR }}\java\{{ JAVA_EXE_FILE }}'
    #when: JDKInstallStatus.exists != True
    
  - name: Install JDK 7
    script: scripts/JDK_Install.ps1 '{{ DOWNLOAD_DIR }}\java\{{ JAVA_VERSION }}' '{{ ansible_env.ProgramFiles }}\jdk{{ JAVA_VERSION }}' '{{ DOWNLOAD_DIR }}\java\JDK_Install.log'
    register: InstallJDKStatus
    #when: JDKInstallStatus.exists != True
    
  - debug: msg='JDK Install status {{ JDKInstallStatus }}'
  
  - name: Set Environment variable JAVA_HOME
    win_environment:
      state: present
      name: JAVA_HOME
      value: '{{ ansible_env.ProgramFiles }}\jdk{{ JAVA_VERSION }}'
      level: user
    when: JDKInstallStatus.exists != True
 
  - name: Add JDK 7 to System PATH
    script: scripts/AddPath.ps1 "%JAVA_HOME%\bin" User
    when: JDKInstallStatus.exists != True