---
  - name: Download JDK 7
    win_get_url:
      url: "{{ DOWNLOAD_URL }}/{{ JAVA_VERSION}}"
      dest: "{{ DOWNLOAD_DIR }}\\java\\{{ JAVA_VERSION }}"

  - name: Install JDK 7
    script: scripts/JDK_Install.ps1 "{{ DOWNLOAD_DIR }}\\java\\{{ JAVA_VERSION }}" "{{ DOWNLOAD_DIR }}\\java\\JDK_Install.log"

  - name: Add JDK 7 to System PATH
    script: scripts/AddPath.ps1 "%JAVA_HOME%\bin" User
