---
  - name: Get JDBC Drivers for Tomcat 7
    win_get_url:
      url: '{{ DOWNLOAD_URL }}/mysql-connector-java-5.1.40-bin.jar'
      dest: '{{ ansible_env.USERPROFILE }}\apache-tomcat-7.0.62\lib\mysql-connector-java-5.1.40-bin.jar'

  - name: Set CLASSPATH to MySQL JConnector
    win_environment:
      state: present
      name: CLASSPATH
      value: '.;%CATALINA_HOME%\lib'
      level: user