---
  #- name: Check for single host
  #  fail: msg="Single host check failed, Please provide your host in Limit parameter of the Job Template"
  #  when: "{{ play_hosts|length }} != 1"
  #
  #- debug: msg='Singe Host Check Passed!, I got executed!'
    
  #- name: Enable Gather Facts
  #  setup:
  #  
  - win_file: path={{ item }} state=directory
    with_items:
      - "{{ DOWNLOAD_DIR }}\\eclipse" 
      - "{{ DOWNLOAD_DIR }}\\git"
      - "{{ DOWNLOAD_DIR }}\\tomcat"
      - "{{ DOWNLOAD_DIR }}\\mysql"
      - "{{ DOWNLOAD_DIR }}\\java"


  - name: Create m2 directroy if not present
    win_file:
      path: '{{ ansible_env.USERPROFILE }}\.m2'
      state: directory

  - name: Copy maven settings
    win_copy:
      src: 'files/settings.xml'
      dest: '{{ ansible_env.USERPROFILE }}\.m2\settings.xml'
